name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  stylua:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Stylua Action
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  nvim:
    name: Neovim Headless Startup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim
      - name: Headless startup
        run: nvim --headless "+qa"
